- hosts: all
  remote_user: vagrant  
  sudo: yes
  sudo_user: root
  vars:
    - fws_config: /etc/fws_server.conf
    - storage_object_module: filtered_websocket.storage_objects.default
    - port: 9000 
    - redis_port: 6543
    - redis_host: 127.0.0.1
    - daemon: fws_daemon
  tasks:
    - name: Install required system packages.
      apt: pkg={{ item }}
           state=latest
           update_cache=yes
      with_items:
        - python-pip
        - python-dev
        - build-essential
      tags:
        - install
        - upgrade-charm

    - name: Pip install filtered_websocket
      pip: name=filtered_websocket
      tags:
        - install
        - config-changed
    
    - name: "Compile {{ daemon }}" 
      template: src={{ daemon }}.j2
                dest=/etc/init.d/{{ daemon }}
                mode=0755
      tags:
        - start
        - config-changed

    - name: "Compile {{ fws_config }}"
      template: src=fws_server.conf.j2
                dest={{ fws_config }}
      tags:
        - start
        - config-changed
    
    - name: Start fws_server
      service: name={{ daemon }} 
               state=running
      tags:
        - start
        - config-changed

    - name: "Install {{ daemon }} as a startup service"
      command: update-rc.d {{ daemon }} defaults
      ignore_errors: true
      tags:
        - start
        - config-changed

    - name: Stop service
      shell: "/etc/init.d/{{ daemon }} stop"
      tags:
        - stop

    - name: "Remove {{ daemon }} as a startup service"
      command: "update-rc.d -f {{ daemon }} remove" 
      tags:
        - stop
